### ISSUE TITLE
Create an ERD (Entity Relationship Diagram) for the Database structure

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#26]
An Entity Relationship Diagram will show each "entity" or table that the database will hold, and their 1:1, 1:many or many:many relationships with the other tables.  

It will also show each attribute, or column, that will be in each table and what data type each column will hold. 

IE: A User entity will have a username: string, password: string etc and will have a 1:many relationship to the Recipes table

**Comment by Dissurender** [comment]
Closing for wrap-up.

![DSD Cohort 2024 - Data Model Structure](https://github.com/bethanyann/dsd-cohort-2024/assets/65290988/79aeb1a0-3608-4724-8e7b-20632e4c4ece)
