### ISSUE TITLE
Project Name Ideas to vote on

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#50]
Write down some project name ideas and we can vote as a team for what we want this project to be called! 

### Task:
Come up with 1-5 names for the project

### Acceptance Criteria:

- [x] Have a list of project names to propose to the group
- [x] Set up a poll in the team chat to have users vote

**Comment by Dissurender** [comment]
GAIA - Got Another Ingredient App (being silly)
Tri-Int - `tree ent`🤷 
Fulcrum
MyGrocer
Mycro

Just spit balling random stuff 💯

**Comment by em-ess** [comment]
Poll has been posted for team in discord.

With additional suggestions
"i cant cook"
"WFD? (what's for dinner?)"

**Comment by em-ess** [comment]
Most votes for: GAIA on discord group chat.
